version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: app/apps/web/Dockerfile
      target: builder # builder レイヤで止めて yarn dev
    command: yarn workspace web dev
    volumes:
      - .:/app
    env_file: .env
    ports:
      - '3002:3000'
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: boilerplate
    ports:
      - '5433:5432'
