version: '3.9'
services:
  web:
    build: ./apps/web
    ports:
      - '3000:3000'
    env_file: .env

  api:
    build: ./apps/api
    depends_on: [db]
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - '8080:8080'

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boilerplate
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  db-data:
