version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: app/apps/web/Dockerfile
    image: boilerplate-web:latest
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: planetscale/pscale:latest # 例：PlanetScale local proxy
    environment:
      DB_NAME: boilerplate
    ports:
      - '3306:3306'
